#pragma once

#define MONROE_ZMQ_DATA_VERSION 1
#define MONROE_ZMQ_DATA_ID_SYSEVENT "MONROE.META.NODE.EVENT"
#define MONROE_ZMQ_DATA_ID_SENSOR   "MONROE.META.NODE.SENSOR"
#define MONROE_ZMQ_DATA_ID_MODEM    "MONROE.META.DEVICE.MODEM"
#define MONROE_ZMQ_DATA_ID_CONNECTIVITY  "MONROE.META.CONNECTIVITY"
#define MONROE_ZMQ_DATA_ID_GPS      "MONROE.META.DEVICE.GPS"

#define MONROE_ZMQ_TOPIC_SYSEVENT   "MONROE.META.NODE.EVENT"
#define MONROE_ZMQ_TOPIC_SENSOR     "MONROE.META.NODE.SENSOR"
#define MONROE_ZMQ_TOPIC_MODEM      "MONROE.META.DEVICE.MODEM"
#define MONROE_ZMQ_TOPIC_CONNECTIVITY    "MONROE.META.DEVICE.CONNECTIVITY"
#define MONROE_ZMQ_TOPIC_GPS        "MONROE.META.DEVICE.GPS"

#define MONROE_ZMQ_TOPIC_MODEM_STATE            "STATE"
#define MONROE_ZMQ_TOPIC_MODEM_MODE             "MODE"
#define MONROE_ZMQ_TOPIC_MODEM_SIGNAL           "SIGNAL"
#define MONROE_ZMQ_TOPIC_MODEM_LTE_BAND         "LTE_BAND"
#define MONROE_ZMQ_TOPIC_MODEM_ISP_NAME         "ISP_NAME"
#define MONROE_ZMQ_TOPIC_MODEM_UPDATE           "UPDATE"
#define MONROE_ZMQ_TOPIC_MODEM_IP_ADDR          "IP_ADDR"
#define MONROE_ZMQ_TOPIC_MODEM_LOC_CHANGE       "LOC_CHANGE"
#define MONROE_ZMQ_TOPIC_MODEM_NW_MCCMNC_CHANGE "NW_MCCMNC_CHANGE"

#define ZMQ_KEY_SEQ            "seq"
#define ZMQ_KEY_TSTAMP         "tstamp"

// these are disabled if -DMONROE is not set
#define ZMQ_KEY_DATAID         "" 
#define ZMQ_KEY_DATAVERSION    ""

#define ZMQ_KEY_CID            "cid"
#define ZMQ_KEY_DEVICE_MODE    "device_mode"
#define ZMQ_KEY_DEVICE_SUBMODE "device_submode"
#define ZMQ_KEY_DEVICE_STATE   "device_state"
#define ZMQ_KEY_ECIO           "ecio"
#define ZMQ_KEY_ENODEB_ID      "enodeb_id"
#define ZMQ_KEY_ICCID          "iccid"
#define ZMQ_KEY_IF_NAME        "if_name"
#define ZMQ_KEY_IMSI           "imsi"
#define ZMQ_KEY_IMSI_MCCMNC    "imsi_mccmnc"
#define ZMQ_KEY_IMEI           "imei"
#define ZMQ_KEY_IP_ADDR        "ip_addr"
#define ZMQ_KEY_INTERNAL_IP_ADDR "internal_ip_addr"
#define ZMQ_KEY_ISP_NAME       "isp_name"
#define ZMQ_KEY_LAC            "lac"
#define ZMQ_KEY_LTE_RSRP       "lte_rsrp"
#define ZMQ_KEY_LTE_FREQ       "lte_freq"
#define ZMQ_KEY_LTE_RSSI       "lte_rssi"
#define ZMQ_KEY_LTE_RSRQ       "lte_rsrq"
#define ZMQ_KEY_LTE_BAND       "lte_band"
#define ZMQ_KEY_LTE_PCI        "lte_pci"
#define ZMQ_KEY_MODE           "mode"
#define ZMQ_KEY_NW_MCCMNC      "nw_mccmnc"
#define ZMQ_KEY_RSCP           "rscp"
#define ZMQ_KEY_RSSI           "rssi"
#define ZMQ_KEY_SIGNAL         "signal"

#define ZMQ_KEY_ALTITUDE      "alt"
#define ZMQ_KEY_LONGITUDE     "lon"
#define ZMQ_KEY_LATITUDE      "lat"
#define ZMQ_KEY_NUMSAT        "num_sat"
#define ZMQ_KEY_NMEA          "nmea_raw"
#define ZMQ_KEY_SPEED         "speed"

#define ZMQ_KEY_INTERFACEID    "interface_id"
#define ZMQ_KEY_INTERFACENAME  "interface_name"
#define ZMQ_KEY_OPERATOR       "operator"

#define ZMQ_TOPIC_RADIO_CELL_LOCATION_GERAN "RADIO.CELL_LOCATION_GERAN"
#define ZMQ_TOPIC_RADIO_GSM_RR_CELL_SEL_RESEL_PARAM "RADIO.GSM_RR_CELL_SEL_RESEL_PARAM"
#define ZMQ_TOPIC_RADIO_GRR_CELL_RESEL "RADIO.GRR_CELL_RESEL"
#define ZMQ_TOPIC_RADIO_GSM_RR_CIPHER_MODE "RADIO.GSM_RR_CIPHER_MODE"
#define ZMQ_TOPIC_RADIO_GSM_RR_CHANNEL_CONF "RADIO.GSM_RR_CHANNEL_CONF"

#define ZMQ_KEY_RADIO_CELL_ID               "cell_id"
#define ZMQ_KEY_RADIO_PLMN                  "plmn"
#define ZMQ_KEY_RADIO_LAC                   "lac"
#define ZMQ_KEY_RADIO_ARFCN                 "arfcn"
#define ZMQ_KEY_RADIO_BSIC                  "bsic"
#define ZMQ_KEY_RADIO_TIMING_ADVANCE        "timing_advance"
#define ZMQ_KEY_RADIO_RX_LEV                "rx_lev"
#define ZMQ_KEY_RADIO_CELL_GERAN_INFO_NMR   "cell_geran_info_nmr"

#define ZMQ_KEY_RADIO_SERVING_BCCH_ARFCN        "serving_bcch_arfcn"
#define ZMQ_KEY_RADIO_SERVING_PBCCH_ARFCN       "serving_pbcch_arfcn"
#define ZMQ_KEY_RADIO_SERVING_PRIORITY_CLASS    "serving_priority_class"
#define ZMQ_KEY_RADIO_SERVING_RXLEV_AVG         "serving_rxlev_avg"
#define ZMQ_KEY_RADIO_SERVING_C1                "serving_c1"
#define ZMQ_KEY_RADIO_SERVING_C2                "serving_c2"
#define ZMQ_KEY_RADIO_SERVING_C31               "serving_c31"
#define ZMQ_KEY_RADIO_SERVING_C32               "serving_c32"
#define ZMQ_KEY_RADIO_SERVING_FIVE_SECOND_TIMER "serving_five_second_timer"
#define ZMQ_KEY_RADIO_CELL_RESELET_STATUS       "cell_reselet_status"
#define ZMQ_KEY_RADIO_RECENT_CELL_SELECTION     "recent_cell_selection"
#define ZMQ_KEY_RADIO_GRR_CELL_NEIGHBORS        "grr_cell_neighbors"
