#pragma once

#define MONROE_ZMQ_DATA_VERSION 1
#define MONROE_ZMQ_DATA_ID_SYSEVENT "MONROE.META.NODE.EVENT"
#define MONROE_ZMQ_DATA_ID_SENSOR   "MONROE.META.NODE.SENSOR"
#define MONROE_ZMQ_DATA_ID_MODEM    "MONROE.META.DEVICE.MODEM"
#define MONROE_ZMQ_DATA_ID_GPS      "MONROE.META.DEVICE.GPS"

#define MONROE_ZMQ_TOPIC_SYSEVENT   "MONROE.META.NODE.EVENT"
#define MONROE_ZMQ_TOPIC_SENSOR     "MONROE.META.NODE.SENSOR"
#define MONROE_ZMQ_TOPIC_MODEM      "MONROE.META.DEVICE.MODEM"
#define MONROE_ZMQ_TOPIC_GPS        "MONROE.META.DEVICE.GPS"

#define MONROE_ZMQ_TOPIC_MODEM_STATE            "STATE"
#define MONROE_ZMQ_TOPIC_MODEM_MODE             "MODE"
#define MONROE_ZMQ_TOPIC_MODEM_SIGNAL           "SIGNAL"
#define MONROE_ZMQ_TOPIC_MODEM_LTE_BAND         "LTE_BAND"
#define MONROE_ZMQ_TOPIC_MODEM_ISP_NAME         "ISP_NAME"
#define MONROE_ZMQ_TOPIC_MODEM_UPDATE           "UPDATE"
#define MONROE_ZMQ_TOPIC_MODEM_IP_ADDR          "IP_ADDR"
#define MONROE_ZMQ_TOPIC_MODEM_LOC_CHANGE       "LOC_CHANGE"
#define MONROE_ZMQ_TOPIC_MODEM_NW_MCCMNC_CHANGE "NW_MCCMNC_CHANGE"

#define ZMQ_KEY_SEQ            "seq"
#define ZMQ_KEY_TSTAMP         "tstamp"

## these are disabled if -DMONROE is not set
#define ZMQ_KEY_DATAID         "" 
#define ZMQ_KEY_DATAVERSION    ""

#define ZMQ_KEY_CID            "cid"
#define ZMQ_KEY_DEVICE_MODE    "device_mode"
#define ZMQ_KEY_DEVICE_SUBMODE "device_submode"
#define ZMQ_KEY_DEVICE_STATE   "device_state"
#define ZMQ_KEY_ECIO           "ecio"
#define ZMQ_KEY_ENODEB_ID      "enodeb_id"
#define ZMQ_KEY_ICCID          "iccid"
#define ZMQ_KEY_IF_NAME        "if_name"
#define ZMQ_KEY_IMSI           "imsi"
#define ZMQ_KEY_IMSI_MCCMNC    "imsi_mccmnc"
#define ZMQ_KEY_IMEI           "imei"
#define ZMQ_KEY_IP_ADDR        "ip_addr"
#define ZMQ_KEY_ISP_NAME       "isp_name"
#define ZMQ_KEY_LAC            "lac"
#define ZMQ_KEY_LTE_RSRP       "lte_rsrp"
#define ZMQ_KEY_LTE_FREQ       "lte_freq"
#define ZMQ_KEY_LTE_RSSI       "lte_rssi"
#define ZMQ_KEY_LTE_RSRQ       "lte_rsrq"
#define ZMQ_KEY_LTE_BAND       "lte_band"
#define ZMQ_KEY_LTE_PCI        "lte_pci"
#define ZMQ_KEY_MODE           "mode"
#define ZMQ_KEY_NW_MCCMNC      "nw_mccmnc"
#define ZMQ_KEY_RSCP           "rscp"
#define ZMQ_KEY_RSSI           "rssi"
#define ZMQ_KEY_SIGNAL         "signal"

#define ZMQ_KEY_ALTITUDE      "alt"
#define ZMQ_KEY_LONGITUDE     "lon"
#define ZMQ_KEY_LATITUDE      "lat"
#define ZMQ_KEY_NUMSAT        "num_sat"
#define ZMQ_KEY_NMEA          "nmea_raw"
#define ZMQ_KEY_SPEED         "speed"

