#pragma once

#define MONROE_ZMQ_DATA_VERSION 1
#define MONROE_ZMQ_DATA_ID_SYSEVENT      "MONROE.META.NODE.EVENT"
#define MONROE_ZMQ_DATA_ID_SENSOR        "MONROE.META.NODE.SENSOR"
#define MONROE_ZMQ_DATA_ID_MODEM         "MONROE.META.DEVICE.MODEM"
#define MONROE_ZMQ_DATA_ID_CONNECTIVITY  "MONROE.META.CONNECTIVITY"
#define MONROE_ZMQ_DATA_ID_GPS           "MONROE.META.DEVICE.GPS"

#define MONROE_ZMQ_TOPIC_SYSEVENT        "MONROE.META.NODE.EVENT"
#define MONROE_ZMQ_TOPIC_SENSOR          "MONROE.META.NODE.SENSOR"
#define MONROE_ZMQ_TOPIC_MODEM           "MONROE.META.DEVICE.MODEM"
#define MONROE_ZMQ_TOPIC_CONNECTIVITY    "MONROE.META.DEVICE.CONNECTIVITY"
#define MONROE_ZMQ_TOPIC_GPS             "MONROE.META.DEVICE.GPS"

#define MONROE_ZMQ_TOPIC_MODEM_STATE            "STATE"
#define MONROE_ZMQ_TOPIC_MODEM_MODE             "MODE"
#define MONROE_ZMQ_TOPIC_MODEM_SIGNAL           "SIGNAL"
#define MONROE_ZMQ_TOPIC_MODEM_LTE_BAND         "LTEBAND"
#define MONROE_ZMQ_TOPIC_MODEM_ISP_NAME         "ISPNAME"
#define MONROE_ZMQ_TOPIC_MODEM_UPDATE           "UPDATE"
#define MONROE_ZMQ_TOPIC_MODEM_IP_ADDR          "IPADDR"
#define MONROE_ZMQ_TOPIC_MODEM_LOC_CHANGE       "LOCCHANGE"
#define MONROE_ZMQ_TOPIC_MODEM_NW_MCCMNC_CHANGE "NWMCCMNCCHANGE"

#define ZMQ_KEY_SEQ            "SequenceNumber"
#define ZMQ_KEY_TSTAMP         "Timestamp"
#define ZMQ_KEY_DATAID         "DataId"
#define ZMQ_KEY_DATAVERSION    "DataVersion"

#define ZMQ_KEY_CID            "CID"
#define ZMQ_KEY_DEVICE_MODE    "DeviceMode"
#define ZMQ_KEY_DEVICE_SUBMODE "DeviceSubmode"
#define ZMQ_KEY_DEVICE_STATE   "DeviceState"
#define ZMQ_KEY_ECIO           "ECIO"
#define ZMQ_KEY_ENODEB_ID      "ENODEBID"
#define ZMQ_KEY_ICCID          "ICCID"
#define ZMQ_KEY_IF_NAME        "InterfaceName"
#define ZMQ_KEY_IMSI           "IMSI"
#define ZMQ_KEY_IMSI_MCCMNC    "IMSIMCCMNC"
#define ZMQ_KEY_IMEI           "IMEI"
#define ZMQ_KEY_IP_ADDR        "IPAddress"
#define ZMQ_KEY_INTERNAL_IP_ADDR "InternalIPAddress"
#define ZMQ_KEY_ISP_NAME       "Operator"
#define ZMQ_KEY_LAC            "LAC"
#define ZMQ_KEY_LTE_RSRP       "RSRP"
#define ZMQ_KEY_LTE_FREQ       "Frequency"
#define ZMQ_KEY_LTE_RSSI       "RSSI"
#define ZMQ_KEY_LTE_RSRQ       "RSRQ"
#define ZMQ_KEY_LTE_BAND       "Band"
#define ZMQ_KEY_LTE_PCI        "PCI"
#define ZMQ_KEY_MODE           "Mode"
#define ZMQ_KEY_NW_MCCMNC      "NWMCCMNC"
#define ZMQ_KEY_RSCP           "RSCP"
#define ZMQ_KEY_RSSI           "RSSI"
#define ZMQ_KEY_SIGNAL         "SignalStrength"

#define ZMQ_KEY_INTERFACEID    "ICCID"
#define ZMQ_KEY_INTERFACENAME  "InterfaceName"
#define ZMQ_KEY_OPERATOR       "MCCMNC"
#define ZMQ_KEY_MODE           "Mode"
#define ZMQ_KEY_SIGNAL         "RSSI"

#define ZMQ_KEY_ALTITUDE       "Altitude"
#define ZMQ_KEY_LONGITUDE      "Longitude"
#define ZMQ_KEY_LATITUDE       "Latitude"
#define ZMQ_KEY_NUMSAT         "SatelliteCount"
#define ZMQ_KEY_NMEA           "NMEA"
#define ZMQ_KEY_SPEED          "Speed"

