#pragma once

#define ZMQ_STYLE_COMPACT 0
#define ZMQ_STYLE_MONROE  1

#define MONROE_ZMQ_DATA_VERSION 2
#define MONROE_ZMQ_DATA_ID_SYSEVENT      "MONROE.META.NODE.EVENT"
#define MONROE_ZMQ_DATA_ID_SENSOR        "MONROE.META.NODE.SENSOR"
#define MONROE_ZMQ_DATA_ID_MODEM         "MONROE.META.DEVICE.MODEM"
#define MONROE_ZMQ_DATA_ID_CONNECTIVITY  "MONROE.META.CONNECTIVITY"
#define MONROE_ZMQ_DATA_ID_GPS           "MONROE.META.DEVICE.GPS"

#define ZMQ_TOPIC_SYSEVENT        "MONROE.META.NODE.EVENT"
#define ZMQ_TOPIC_SENSOR          "MONROE.META.NODE.SENSOR"
#define ZMQ_TOPIC_MODEM           "MONROE.META.DEVICE.MODEM"
#define ZMQ_TOPIC_CONNECTIVITY    "MONROE.META.DEVICE.CONNECTIVITY"
#define ZMQ_TOPIC_GPS             "MONROE.META.DEVICE.GPS"

#define ZMQ_TOPIC_MODEM_STATE            "STATE"
#define ZMQ_TOPIC_MODEM_MODE             "MODE"
#define ZMQ_TOPIC_MODEM_SIGNAL           "SIGNAL"
#define ZMQ_TOPIC_MODEM_LTE_BAND         "LTEBAND"
#define ZMQ_TOPIC_MODEM_ISP_NAME         "ISPNAME"
#define ZMQ_TOPIC_MODEM_UPDATE           "UPDATE"
#define ZMQ_TOPIC_MODEM_IP_ADDR          "IPADDR"
#define ZMQ_TOPIC_MODEM_LOC_CHANGE       "LOCCHANGE"
#define ZMQ_TOPIC_MODEM_NW_MCCMNC_CHANGE "NWMCCMNCCHANGE"

#define ZMQ_TOPIC_RADIO_CELL_LOCATION_GERAN "RADIO.CELL_LOCATION_GERAN"
#define ZMQ_TOPIC_RADIO_GSM_RR_CELL_SEL_RESEL_PARAM "RADIO.GSM_RR_CELL_SEL_RESEL_PARAM"
#define ZMQ_TOPIC_RADIO_GRR_CELL_RESEL "RADIO.GRR_CELL_RESEL"
#define ZMQ_TOPIC_RADIO_GSM_RR_CIPHER_MODE "RADIO.GSM_RR_CIPHER_MODE"
#define ZMQ_TOPIC_RADIO_GSM_RR_CHANNEL_CONF "RADIO.GSM_RR_CHANNEL_CONF"

#define ZMQ_KEY_SEQ            0
#define ZMQ_KEY_TSTAMP         1
#define ZMQ_KEY_DATAID         2
#define ZMQ_KEY_DATAVERSION    3

#define ZMQ_KEY_CID            4
#define ZMQ_KEY_DEVICE_MODE    5
#define ZMQ_KEY_DEVICE_SUBMODE 6
#define ZMQ_KEY_DEVICE_STATE   7
#define ZMQ_KEY_ECIO           8
#define ZMQ_KEY_ENODEB_ID      9
#define ZMQ_KEY_ICCID          10
#define ZMQ_KEY_IF_NAME        11
#define ZMQ_KEY_IIF_NAME       12
#define ZMQ_KEY_IMSI           13
#define ZMQ_KEY_IMSI_MCCMNC    14
#define ZMQ_KEY_IMEI           15
#define ZMQ_KEY_IP_ADDR        16
#define ZMQ_KEY_INTERNAL_IP_ADDR 17
#define ZMQ_KEY_ISP_NAME       18
#define ZMQ_KEY_LAC            19
#define ZMQ_KEY_LTE_RSRP       20
#define ZMQ_KEY_LTE_FREQ       21
#define ZMQ_KEY_LTE_RSSI       22
#define ZMQ_KEY_LTE_RSRQ       23
#define ZMQ_KEY_LTE_BAND       24
#define ZMQ_KEY_LTE_PCI        25
#define ZMQ_KEY_MODE           26
#define ZMQ_KEY_NW_MCCMNC      27
#define ZMQ_KEY_RSCP           28
#define ZMQ_KEY_RSSI           29

#define ZMQ_KEY_INTERFACEID    30
#define ZMQ_KEY_INTERFACENAME  31
#define ZMQ_KEY_OPERATOR       32
#define ZMQ_KEY_SIGNAL         34

#define ZMQ_KEY_ALTITUDE       35
#define ZMQ_KEY_LONGITUDE      36
#define ZMQ_KEY_LATITUDE       37
#define ZMQ_KEY_NUMSAT         38
#define ZMQ_KEY_NMEA           39
#define ZMQ_KEY_SPEED          40

#define ZMQ_KEY_RADIO_CELL_ID               46
#define ZMQ_KEY_RADIO_PLMN                  47
#define ZMQ_KEY_RADIO_LAC                   48
#define ZMQ_KEY_RADIO_ARFCN                 49
#define ZMQ_KEY_RADIO_BSIC                  50
#define ZMQ_KEY_RADIO_TIMING_ADVANCE        51
#define ZMQ_KEY_RADIO_RX_LEV                52
#define ZMQ_KEY_RADIO_CELL_GERAN_INFO_NMR   53

#define ZMQ_KEY_RADIO_SERVING_BCCH_ARFCN        54
#define ZMQ_KEY_RADIO_SERVING_PBCCH_ARFCN       55
#define ZMQ_KEY_RADIO_SERVING_PRIORITY_CLASS    56
#define ZMQ_KEY_RADIO_SERVING_RXLEV_AVG         57
#define ZMQ_KEY_RADIO_SERVING_C1                58
#define ZMQ_KEY_RADIO_SERVING_C2                59
#define ZMQ_KEY_RADIO_SERVING_C31               60
#define ZMQ_KEY_RADIO_SERVING_C32               61
#define ZMQ_KEY_RADIO_SERVING_FIVE_SECOND_TIMER 62
#define ZMQ_KEY_RADIO_CELL_RESELET_STATUS       63
#define ZMQ_KEY_RADIO_RECENT_CELL_SELECTION     64
#define ZMQ_KEY_RADIO_GRR_CELL_NEIGHBORS        65

#define ZMQ_KEY_RADIO_CIPHERING_STATE       66
#define ZMQ_KEY_RADIO_CIPHERING_ALGORITHM   67

#define ZMQ_KEY_RADIO_CELL_RESELECT_HYSTERESIS  68
#define ZMQ_KEY_RADIO_MS_TXPWR_MAX_CCH          69
#define ZMQ_KEY_RADIO_RXLEV_ACCESS_MIN          70
#define ZMQ_KEY_RADIO_POWER_OFFSET_VALID        71
#define ZMQ_KEY_RADIO_POWER_OFFSET              72
#define ZMQ_KEY_RADIO_NECI                      73
#define ZMQ_KEY_RADIO_ACS                       74
#define ZMQ_KEY_RADIO_OPT_RESELECT_PARAM_IND    75
#define ZMQ_KEY_RADIO_CELL_BAR_QUALIFY          76
#define ZMQ_KEY_RADIO_CELL_RESELECT_OFFSET      77
#define ZMQ_KEY_RADIO_TEMPORARY_OFFSET          78
#define ZMQ_KEY_RADIO_PENALTY_TIME              79

#define ZMQ_KEY_RADIO_NUM_DED_CHANS 80
#define ZMQ_KEY_RADIO_DTX_INDICATOR 81
#define ZMQ_KEY_RADIO_POWER_LEVEL   82
#define ZMQ_KEY_RADIO_STARTING_TIME_VALID 83
#define ZMQ_KEY_RADIO_STARTING_TIME 84
#define ZMQ_KEY_RADIO_CIPHER_FLAG   85
#define ZMQ_KEY_RADIO_CIPHER_ALGORITHM 86
#define ZMQ_KEY_RADIO_AFTER_CHANNEL_CONFIG  87
#define ZMQ_KEY_RADIO_BEFORE_CHANNEL_CONFIG 88
#define ZMQ_KEY_RADIO_CHANNEL_MODE_1 89
#define ZMQ_KEY_RADIO_CHANNEL_MODE_2 90

char* zmq_fields_compact[91];
char* zmq_fields_monroe[91];
